PortFolio/Controllers/UserRegistrationController.cs
using PortFolio.BDEntity;
using PortFolio.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PortFolio.Controllers
{
    public class UserRegistrationController : Controller
    {
        private PortFolioEntities db = new PortFolioEntities();
        // GET: UserRegistration
        public ActionResult Index()
        {
            RegistrationViewModel model = new RegistrationViewModel();
        
            var list = db.RegistrationTbls.ToList();
            List<RegistrationViewModel> TempList = new List<RegistrationViewModel>();

            foreach (var item in list)
            {
                var obj = new RegistrationViewModel
                {
                    Id = item.Id,
                    Name = item.Name,
                    MobileNo = item.Mobile,
                    BirthDate = item.BirthDate,
                    Email = item.Email
                };
                TempList.Add(obj);
            }
            model.RegistrationList = TempList;
            return View(model);
        }

        // GET: UserRegistration/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: UserRegistration/Create
        public ActionResult Create()
        {
            RegistrationViewModel model = new RegistrationViewModel();

            dynamic countryList = db.CountryTbls.ToList();

            var list = new List<SelectListItem>();
            foreach (var item in countryList)
            {
                list.Add(new SelectListItem()
                {
                    Text = item.Name,
                    Value = item.Id.ToString()
                });
            }
            model.CountryList = list;
            return View(model);
        }

        // POST: UserRegistration/Create
        [HttpPost]
        public ActionResult Create(RegistrationViewModel model, HttpPostedFileBase file)
        {
            try
            {
                RegistrationTbl tbl = new RegistrationTbl();
                tbl.Name = model.Name;
                tbl.CountryId = model.CountryId;
                tbl.BirthDate = model.BirthDate;
                tbl.Email = model.Email;
                tbl.Mobile = model.MobileNo;

                tbl.ImageName = file.ContentType;

                Int32 length = file.ContentLength;
                byte[] tempImage = new byte[length];
                file.InputStream.Read(tempImage, 0, length);
                tbl.Image = tempImage;

                db.RegistrationTbls.Add(tbl);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: UserRegistration/Edit/5
        public ActionResult Edit(int id)
        {
            RegistrationViewModel model = new RegistrationViewModel();
            var entity = db.RegistrationTbls.Find(id);

            model.Name = entity.Name;
            model.CountryId = entity.CountryId;
            model.Email = entity.Email;
            model.MobileNo = entity.Mobile;
            model.BirthDate = entity.BirthDate;
            model.Image = entity.Image;
            return View(model);
        }

        // POST: UserRegistration/Edit/5
        [HttpPost]
        public ActionResult Edit(RegistrationViewModel model, HttpPostedFileBase file)
        {
            try
            {
                RegistrationTbl tbl = new RegistrationTbl();
                tbl.Id = model.Id;
                tbl.Name = model.Name;
                tbl.CountryId = model.CountryId;
                tbl.BirthDate = model.BirthDate;
                tbl.Email = model.Email;
                tbl.Mobile = model.MobileNo;
                tbl.ImageName = model.ImageName;
                tbl.Image = model.Image;
                if (file != null)
                {
                    tbl.ImageName = file.ContentType;

                    Int32 length = file.ContentLength;
                    byte[] tempImage = new byte[length];
                    file.InputStream.Read(tempImage, 0, length);
                    tbl.Image = tempImage;
                }
                db.Entry(tbl).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View(model);
            }
        }

        // GET: UserRegistration/Delete/5
        public ActionResult Delete(int id)
        {
            RegistrationTbl registrationTbl = db.RegistrationTbls.Find(id);
            db.RegistrationTbls.Remove(registrationTbl);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: UserRegistration/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

PortFolio/Views/UserRegistration/Create.cshtml
@model PortFolio.Models.RegistrationViewModel

@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>Create</h2>


@using (Html.BeginForm("Create", "UserRegistration", FormMethod.Post,  new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>RegistrationTbl</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
               @Html.DropDownListFor(model => model.CountryId, Model.CountryList, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <span id="portrait-holder" class="applicant-img-preview">
                    <img id="previewImg" class="applicant-img-preview" src="#" alt="" />
                </span>
                <input id="File" type="file" name="File" onchange="readURL(this);" />
             </div>
            </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}


<script type="text/javascript">
     function readURL(input) {
         if (input.files && input.files[0]) {
             var reader = new FileReader();

             reader.onload = function (e) {
                 $('#previewImg')
                     .attr('src', e.target.result)
                     .width(150)
                     .height(200);
             };

             reader.readAsDataURL(input.files[0]);
         }
     }
</script>

PortFolio/Views/UserRegistration/Edit.cshtml
@model PortFolio.Models.RegistrationViewModel

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@using (Html.BeginForm("Edit", "UserRegistration", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
<div class="form-horizontal">
    <h4>RegistrationTbl</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.CountryId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.CountryId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.CountryId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.BirthDate, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.BirthDate, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.BirthDate, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MobileNo, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MobileNo, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MobileNo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Image", htmlAttributes: new { @class = "control-label col-md-2" })
           <div class="col-md-10">
            @if (Model.Image != null)
            {
                <span id="portrait-holder" class="applicant-img-preview">
                    <img src="data:image/png;base64,@System.Convert.ToBase64String(Model.Image)" width="100" height="150"/>
                </span>
            }
                    @Html.HiddenFor(model => model.Image)
                    @Html.HiddenFor(model => model.ImageName)

                    <img id="previewImg" class="applicant-img-preview" src="#" alt="" />
           
               <input id="File" type="file" name="File" onchange="readURL(this);" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

<script type="text/javascript">
    function readURL(input) {
        $('#portrait-holder').hide();
         if (input.files && input.files[0]) {
             var reader = new FileReader();

             reader.onload = function (e) {
                 $('#previewImg')
                     .attr('src', e.target.result)
                     .width(100)
                     .height(150);
             };

             reader.readAsDataURL(input.files[0]);
         }
     }
</script>

PortFolio/Views/UserRegistration/Index.cshtml
@model PortFolio.Models.RegistrationViewModel
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.BirthDate)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.MobileNo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model.RegistrationList)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.BirthDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.MobileNo)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>